### ISSUE TITLE
exec not working can't get variables and pulling all key /values 

### ISSUE THREAD

**Issue by raiknet** [channable/vaultenv#109]
I'm trying to pass on env. variables to  a program. To simplify the issue, I was able to replicate it with the Linux command "echo". This works in my docker ubuntu container:
`vaultenv  env` = list all variables from the container and from Vault
this also works vaultenv  /bin/echo $LANG (inherited variable) 
This returns nothing 'vaultenv  /bin/echo $DB_HOST'.
2nd question:
Is there a way to load all key /values from with default names from VAULT with specifying all in the secret file like: 

VERSION 2 
MOUNT dev
env#* (all K/V under dev )

Thank you

**Comment by joris-burgers** [comment]
Hi @raiknet,

Thansk for your interest in `vaultenv`!

To answer your first question, it seems that the problem here is not so much `vaultenv`, but your shell. I managed to reproduce your problem and it looks to me like your shell is replacing your environment variable before the call to `vaultenv`. 

Take `vaultenv /bin/echo $DB_HOST`. The first step would be to do a lookup of the environment variable in the current environment, which results in the call `vaultenv /bin/echo ''`. After this, no more environment variables exists in you `echo` call, so none will be printed from the `vaultenv` environment. To solve this, you could add a separate script, like `echo_env`:
```bash
#!/usr/bin/env bash

/bin/echo $DB_HOST
```
After this, the script is called using `vaultenv ./echo_env`. This will evaluate the environment variable in the correct environment, meaning the environment `vaultenv` created for you.


To answer your second questions, in short, no, there is no way to currently do this. The `vault` API does allow us to list all keys in some path, which can be used recursively to create a tree of all possible keys, but only individual secrets can be retrieved. The combination of these 2 endpoints would in theory allow us to retrieve all keys or keys with a wildcard, but that is currently not yet possible. 

Hope this helps!

**Comment by raiknet** [comment]
Thank you again, it's working now.
