### ISSUE TITLE
Support aeson 2.0

### ISSUE THREAD

**Issue by sternenseemann** [channable/vaultenv#118]
This would be great, as it'd allow building vaultenv using the latest stackage (LTS) solver.

**Comment by ReinierMaas** [comment]
This is a major version bump see https://github.com/haskell/aeson/blob/HEAD/changelog.md.

We have Nix packages pinned at [`unstable`](https://github.com/NixOS/nixpkgs/commit/65f4c39a40e6ed4343dd94017c3ed81f416cd3b4). We want to update the pin because in the latest `unstable` version of Nix packages there already was a push to make more packages compatible with `aeson 2.0.*` and `GHC 9.02`, see [call-for-contributions-we-are-updating-to-ghc-9-0-2](https://discourse.nixos.org/t/call-for-contributions-we-are-updating-to-ghc-9-0-2/17844). Because of this push selecting `GHC 9.02` our migrations first step (PR) should move from `GHC 8.65` to `GHC 9.02`. In a later step, we could migrate from `aeson 1.5.*` to `aeson 2.0.*`.

We currently select ['haskellPackages.aeson'](https://search.nixos.org/packages?channel=unstable&show=haskellPackages.aeson&from=0&size=50&sort=relevance&type=packages&query=aeson) which is at `1.5.6.0`.
We could select ['haskellPackages.aeson_2_0_3_0'](https://search.nixos.org/packages?channel=unstable&show=haskellPackages.aeson_2_0_3_0&from=0&size=50&sort=relevance&type=packages&query=aeson) which is at `2.0.3.0`.

---

I have changed the [GHC version](https://github.com/channable/vaultenv/pull/119) we use and tried to select the `aeson 2.0.3.0` package, we have some dependencies that are not ready for this migration. These could not be resolved:

```
Setup: Encountered missing or private dependencies:
OneTuple >=0.3.1 && <0.4,
attoparsec >=0.14.2 && <0.15,
hashable >=1.3.5.0 && <1.5,
quickcheck-instances >=0.3.26.1 && <0.4,
time-compat >=1.9.6 && <1.10
```

Selecting `aeson 2.0.3.0` can be done by updating the following line:

https://github.com/channable/vaultenv/blob/e9d5689d7c18ecd458ea4fb39c955792bbc03750/nix/haskell-dependencies.nix#L6

You can then test whether you can build the code by running:

```
nix run -c stack build
```

---

Please let us know if you would like to pick up the second step of the migration.

**Comment by sternenseemann** [comment]
I'm writing precisely because of the nixpkgs migration. We'll be building `vaultenv` with `aeson` 1.5.6.0 going forward, but would like to be able to drop that workaround in the future. 

> Please let us know if you would like to pick up the second step of the migration.

I'd appreciate upstream helping us out here. he migration left us with thousands of newly broken packages we have been trying to fix most of. Sadly we don't have unlimited time on our hands and will thus prefer a quick workaround over preparing a patch.

**Comment by ReinierMaas** [comment]
Thanks for your request `vaultenv` master branch is now built with `GHC 9.0.2` and `aeson 2.0.*`.
We do still need to override the `hashable` package to version `1.4.0.2` in Nix.
